on:
  push:
    branches: ["master"]

jobs:
  native_build:
    runs-on: ubuntu-latest
    name: Build Application
    steps:
      - name: Checkout the code
        uses: actions/checkout@master
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build
