on:
  push:
    branches: ["master", "native"]

env:
  PROJECT_ID: wagon-bootcamp-374809
  GAR_LOCATION: europe-west2
  #  https://console.cloud.google.com/artifacts/docker/wagon-bootcamp-374809/europe-west2/personal-projects?project=wagon-bootcamp-374809
  REPOSITORY: personal-projects
  SERVICE: swimlane
  REGION: europe-west2

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Application
    steps:
      - name: Checkout the code
        uses: actions/checkout@master

      - name: Docker Auth
        id: docker-auth
        uses: 'docker/login-action@v1'
        with:
          registry: ${{ env.GAR_LOCATION }}-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build with Gradle
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        with:
          arguments: |-
            build
            -Dquarkus.package.type=native
            -Dquarkus.container-image.build=true
            -Dquarkus.container-image.image=${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}
            -Dquarkus.container-image.push=true

  deploy:
    name: Deploy Image to Cloud Run
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v1'
        with:
         credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}

    environment:
        name: production
        url: ${{ steps.deploy.outputs.url }}/q/swagger-ui/
